name: Sprint_9 autotests
on:
  push:
    branches:
      develop
jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0
      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test_docker